[[video]]
video_filename = "output_blue_larger_res_hexagrid.mp4"
#watermark_filename = "v=grid1.png=(grid2.png=grid3.png)"
#clip_rect = { x = 128, y = 128, end_x = 896, end_y = 640 }
#watermark_home = "images"
#watermark_filename = "H=grid1.png=(grid2.png=grid3.png)"
#watermark_position = [-2, -2]
#watermark_dimension = 200
#clip_rect = "11ee"
#clip_rect = "22dd"

start_time = "0"
end_time = "2"

desc = "hexagrid zoom test"

[[video.segments]]
## should be 4x2 blocks tl at (0, 1).
## and it does generate that, if no union rect forces it to be larger.
#clip_rect = "0132"
#clip_rect = "0077"

# 6x4 TL
clip_rect = "0053"


[[video.segments]]
# breaks things, cos makes a rect outside the video.
# need to rectify the rect to be inside the image.
#clip_rect = "0037"

# this fails - because it extends out of top of input video
#  -- NOW WORKS after minimal move inside etc.
#clip_rect = "0001"
#clip_rect = "f0ff"

# 4x4 TR
clip_rect = "c0f3"
#clip_rect = "a0f3"


#
#
#[[video.segments]]
#clip_rect = "44bb"
