[[video]]
video_filename = "output_blue_larger_res_hexagrid.mp4"
#watermark_filename = "v=grid1.png=(grid2.png=grid3.png)"
#clip_rect = { x = 128, y = 128, end_x = 896, end_y = 640 }
watermark_home = "images"
#watermark_filename = "H=grid1.png"
#watermark_filename = "H=grid1.png=(grid2.png=grid3.png)"
watermark_position = [0, 0]
#watermark_dimension = 200
#clip_rect = "11ee"
#clip_rect = "22dd"

#max_pixel_scale = 2
# can this even be used? does it make sense?
# ah yes, if you make output_video_size < input video size, things are getting
# pixel scales <1.
# TODO later.
#min_pixel_scale = 2


start_time = "0"
end_time = "0.5"

# overrides automatic detection of union largest size as output video size
#output_video_size = [768, 576]
#output_video_size = [384, 288]
#output_video_size = [1024, 768]
# to avoid squish when output_video_size aspect diff from input video,
# we want to fill our max_output_size into the output_video_size? or similar
#output_video_size = [512, 768]


desc = "hexagrid zoom test"



#[[video.segments]]
#clip_rect = "00ff"

#[[video.segments]]
### should be 4x2 blocks tl at (0, 1).
### and it does generate that, if no union rect forces it to be larger.
##clip_rect = "0132"
##clip_rect = "0077"
#
## issues:
## 0053,0fff
## 0053, 0d0f (shows just one square for the last!)
##
## ok: 0053, 0f0f. 11
#
## is this fit vs. fill? Or an issue with w ratio < , h ratio > for the fit/fill?
#
## 6x4 TL
##clip_rect = "0053"
#clip_rect = "0035"


#[[video.segments]]
## breaks things, cos makes a rect outside the video.
## need to rectify the rect to be inside the image.
##clip_rect = "0037"
#
## this fails - because it extends out of top of input video
##  -- NOW WORKS after minimal move inside etc.
##clip_rect = "0001"
##clip_rect = "f0ff"
#
## 4x4 TR
##clip_rect = "c0f3"
##clip_rect = "a0f3"
#
## now this breaks after using min, max!
## 3x16
#clip_rect = "0f2f"
##clip_rect = "0e0f"


# 1x1
[[video.segments]]
clip_rect = "0101"

# 2x1
[[video.segments]]
clip_rect = "0111"

# 3x1
[[video.segments]]
clip_rect = "0121"

# 4x1
[[video.segments]]
clip_rect = "0131"

# 4x3
[[video.segments]]
clip_rect = "0133"

# 6x3
[[video.segments]]
clip_rect = "0153"

#[[video.segments]]
#clip_rect = "0000"
#
#[[video.segments]]
#clip_rect = "0010"
#
#[[video.segments]]
#clip_rect = "0020"
#
#[[video.segments]]
#clip_rect = "0030"
#
#[[video.segments]]
#clip_rect = "0032"

#
#[[video.segments]]
#clip_rect = "0040"
#
#[[video.segments]]
#clip_rect = "0050"
#
#[[video.segments]]
#clip_rect = "0060"
#
#[[video.segments]]
#clip_rect = "0070"
#
#[[video.segments]]
#clip_rect = "0080"
#
#[[video.segments]]
#clip_rect = "0090"
#
#[[video.segments]]
#clip_rect = "00b0"
#
#[[video.segments]]
#clip_rect = "00d0"
#
#[[video.segments]]
#clip_rect = "00f0"
#
#
#
#
#
#[[video.segments]]
#clip_rect = "0000"
##
##[[video.segments]]
##clip_rect = "0001"
#
##[[video.segments]]
##clip_rect = "0002"
##
#[[video.segments]]
#clip_rect = "0003"
#
##[[video.segments]]
##clip_rect = "0004"
#
##[[video.segments]]
##clip_rect = "0005"
##
##[[video.segments]]
##clip_rect = "0006"
#
#[[video.segments]]
#clip_rect = "0007"
#
##[[video.segments]]
##clip_rect = "0009"
#
#[[video.segments]]
#clip_rect = "000a"
#
##[[video.segments]]
##clip_rect = "000b"
##
##[[video.segments]]
##clip_rect = "000d"
#
#[[video.segments]]
#clip_rect = "000f"
